### ISSUE TITLE
Segfault in pthread with --threadprofiler

### ISSUE THREAD

**Issue by GENETX** [pilight/pilight#154]
On OpenSUSE 13.2 x64, pilight-deamon -D --threadprofiler segfaults.

Config:
```
{
	"devices": {
		"switch1": {
			"protocol": [ "elro_400" ],
			"id": [{
				"systemcode": 0,
				"unitcode": 15
			}],
			"state": "off"
		}
	},
	"rules": {},
	"gui": {
		"switch1": {
			"name": "switch1",
			"group": [ "Woonkamer" ],
			"media": [ "all" ],
			"readonly": 0
		}
	},
	"settings": {
		"log-level": 4,
		"pid-file": "/var/run/pilight.pid",
		"log-file": "/var/log/pilight.log",
		"send-repeats": 10,
		"receive-repeats": 1,
		"webserver-enable": 1,
		"webserver-root": "/usr/local/share/pilight/",
		"webserver-port": 5001,
		"webserver-cache": 1
	},
	"hardware": {
		"433nano": {
			"comport": "/dev/ttyUSB0"
		}
	},
	"registry": {
		"pilight": {
			"version": {
				"current": "6.0"
			}
		}
	}
}
```

Version: pilight-daemon version 6.0, commit d8f1f7f

Pilight.err:
- Empty

pilight.log
```
[Mar 15 16:32:11:658242] pilight-daemon: INFO: version 6.0, commit d8f1f7f
[Mar 15 16:32:11:764894] pilight-daemon: ERROR: ----- Thread Profiling -----
[Mar 15 16:32:11:767800] pilight-daemon: ERROR: - thread lirc: 0.000000%
[Mar 15 16:32:11:768171] pilight-daemon: ERROR: - thread socket: 0.000000%
[Mar 15 16:32:11:768467] pilight-daemon: ERROR: - thread ssdp: 0.000000%
[Mar 15 16:32:11:768663] pilight-daemon: ERROR: - thread sender: 0.000000%
[Mar 15 16:32:11:768804] pilight-daemon: ERROR: - thread broadcaster: 0.000000%
[Mar 15 16:32:11:769010] pilight-daemon: ERROR: - thread 433nano: 0.000000%
[Mar 15 16:32:11:769147] pilight-daemon: ERROR: - thread receive parser: 0.000000%
[Mar 15 16:32:11:769336] pilight-daemon: ERROR: - thread events client: 0.000000%
[Mar 15 16:32:11:769481] pilight-daemon: ERROR: - thread events loop: 0.000000%
```

GDB Output:
```
(gdb) run -D --threadprofiler
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /home/gerwin/Temp/pilight/pilight-daemon -D --threadprofiler
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[Mar 15 16:37:14:964654] pilight-daemon: INFO: version 6.0, commit d8f1f7f
[New Thread 0x7ffff679e700 (LWP 21193)]
[New Thread 0x7ffff5f9d700 (LWP 21194)]
[New Thread 0x7ffff579c700 (LWP 21195)]
[New Thread 0x7ffff4f9b700 (LWP 21196)]
[New Thread 0x7fffe7fff700 (LWP 21197)]
[New Thread 0x7fffe77fe700 (LWP 21198)]
[New Thread 0x7fffe6ffd700 (LWP 21199)]
[ Mar 15 16:37:15:85425] pilight-daemon: ERROR: ----- Thread Profiling -----
[ Mar 15 16:37:15:85503] pilight-daemon: ERROR: - thread lirc: 0.000000%
[ Mar 15 16:37:15:85542] pilight-daemon: ERROR: - thread socket: 0.000000%
[ Mar 15 16:37:15:85563] pilight-daemon: ERROR: - thread ssdp: 0.000000%
[ Mar 15 16:37:15:85583] pilight-daemon: ERROR: - thread sender: 0.000000%
[ Mar 15 16:37:15:85600] pilight-daemon: ERROR: - thread broadcaster: 0.000000%
```
```
Program received signal SIGSEGV, Segmentation fault.
pthread_getcpuclockid (threadid=0, clockid=0x7fffffffe11c) at ../nptl/sysdeps/unix/sysv/linux/pthread_getcpuclockid.c:35
35        if (INVALID_TD_P (pd))
(gdb) backtrace
#0  pthread_getcpuclockid (threadid=0, clockid=0x7fffffffe11c) at ../nptl/sysdeps/unix/sysv/linux/pthread_getcpuclockid.c:35
#1  0x00007ffff7afe7bf in getThreadCPUUsage () from /usr/local/lib/libpilight.so
#2  0x00007ffff7b06851 in threads_cpu_usage () from /usr/local/lib/libpilight.so
#3  0x000000000040ac60 in pilight_stats ()
#4  0x000000000040b197 in main ()
```
```
(gdb) frame 0
#0  pthread_getcpuclockid (threadid=0, clockid=0x7fffffffe11c) at ../nptl/sysdeps/unix/sysv/linux/pthread_getcpuclockid.c:35
35        if (INVALID_TD_P (pd))
```

OS: OpenSUSE 13.1 x64
`uname -a`:
```
Linux mediaserver 3.19.0-1.g8a7d5f9-desktop #1 SMP PREEMPT Wed Feb 11 08:59:56 UTC 2015 (8a7d5f9) x86_64 x86_64 x86_64 GNU/Linux
```
The platform is a normal PC, A celeron G1610 to be specific

`./pilight-daemon -D --threadprofiler` will repoduce this error always on my machine

**Comment by CurlyMoo** [comment]
Please post according to these rules https://github.com/pilight/pilight/blob/master/CONTRIBUTING.md which you also saw when opening the issue.

**Comment by CurlyMoo** [comment]
Can you check if it's fixed?

**Comment by GENETX** [comment]
Yes I can! This one is fixed :)
